#ifndef SRC_ADDRESS_CONSTANTS_H_
#define SRC_ADDRESS_CONSTANTS_H_

#include "xparameters.h"

// peripheral addresses
#define DMA_MM2S_ADDR XPAR_MB_DMA_MM2S_AXI_BRAM_CTRL_0_S_AXI_BASEADDR
#define FIFO_COUNT_ADDR (XPAR_AXI_GPIO_FIFO_RNG_0_BASEADDR)
#define TRNG_READ_ADDR (XPAR_AXI_GPIO_FIFO_RNG_0_BASEADDR+0x0008)

#endif /* SRC_ADDRESS_CONSTANTS_H_ */
