#!/usr/bin/env python3
"""
Description: Creates device specific secrets
Use: Once per device
"""
from functools import reduce
import binascii
import os
import json
from argparse import ArgumentParser

import pyhy
from Crypto.Random import get_random_bytes

def main(region_names, user_names, user_secrets, region_secrets, device_dir, outfile):
    publics_file_name = "device_publics.h"
    secrets_file_name = "device_secrets.h"

    # Generate keys.
    system_symmetric_key = get_random_bytes(16)
    system_ecc_key = pyhy.hydro_sign_keygen()
    system_ecc_key_priv = bytes(system_ecc_key.sk)
    system_ecc_key_pub = bytes(system_ecc_key.pk)
    system_pwhash_master_key = bytes(pyhy.hydro_pwhash_keygen())
    system_sharing_key = bytes(pyhy.hydro_secretbox_keygen())

    # create device directory
    try:
        os.mkdir(device_dir)
    except Exception as e:
        print("Could not create directory {device_dir}: {e}".format(device_dir=device_dir, e=e))
        return

    # create device secrets file
    try:
        device_secrets = open(os.path.join(device_dir, secrets_file_name), "w")
        device_publics = open(os.path.join(device_dir, publics_file_name), "w")
    except Exception as e:
        print("Unable to open secrets file: {e}".format(e=e))
        return

    # Create file for storing the system secrets between provisionings.
    try:
        system_secrets = open(outfile, "w+")
    except Exception as e:
        print("Unable to open secrets file: {e}".format(e=e))
        return

    # check for valid region names
    try:
        rids = [str(region_secrets[r][0]) for r in region_names]
        region_keys = [binascii.unhexlify(region_secrets[r][1]) for r in region_names]
    except Exception as e:
        print("Unable to create secrets file: {e} "
              "Please ensure all regions entered are in the list: {user_secrets}".format(e=e, user_secrets=user_secrets.keys()))
        return

    # check for valid user names
    try:
        uids = [str(user_secrets[u]['id']) for u in usernames]
    except Exception as e:
        print("Unable to create secrets file: {e} "
              "Please ensure all regions entered are in the list: {user_secrets}".format(e=e, user_secrets=user_secrets.keys()))
        return

    hash_pin = lambda pin: pyhy.hydro_pwhash_deterministic(pin.encode(), "AAAAAAAA", system_pwhash_master_key, 10000, 0, 1)
    create_bv = lambda l: reduce(int.__or__, [int(i) for i in l], 0)

    # Sharing integrity: system_sharing_MAC_key
    # Sharing public keys: user_sharing_public_keys (just made up this name)

    # write secrets
    device_secrets.write(f'''
#ifndef SECRETS_H
#define SECRETS_H

const u8 system_integrity_ECC_key[] = {{ {",".join(hex(b) for b in system_ecc_key_pub)} }};
const u8 system_preview_AES_key[] = {{ {",".join(hex(b) for b in system_symmetric_key)} }};
const u8 system_pwhash_key[] = {{ {",".join(hex(b) for b in system_pwhash_master_key)} }};

const u8 REGION_KEYS[][64] = {{ {"{ " + " }, { ".join(",".join(hex(b) for b in key) for key in region_keys) + " }"} }};
const u8 system_region_AES_keys[][64] = {{ {"{ " + " }, { ".join(",".join(hex(b) for b in key) for key in region_keys) + " }"} }};

const u8 system_sharing_key[] = {{ {",".join(hex(b) for b in system_sharing_key)} }};

#endif // SECRETS_H
''')

    device_publics.write(f'''
#ifndef PUBLICS_H
#define PUBLICS_H

#define NUM_REGIONS {len(region_secrets)}
const char *REGION_NAMES[] = {{ {", ".join(['"' + r + '"' for r in region_secrets])} }};
const u8 REGION_IDS[] = {{ {", ".join([str(r[0]) for r in region_secrets.values()])} }};

#define NUM_PROVISIONED_REGIONS {len(region_names)}
const u64 PROVISIONED_RIDS = {create_bv(rids)};

#define NUM_USERS {len(user_secrets)}
const char *USERNAMES[] = {{ {", ".join(['"' + u + '"' for u in user_secrets])} }};
const u8 USER_IDS[] = {{ {", ".join([str(user_secrets[u]['id']) for u in user_names])} }};

#define NUM_PROVISIONED_USERS {len(user_names)}
const u64 PROVISIONED_UIDS = {create_bv(uids)};
const u8 PROVISIONED_PINS[][64] = {{ {"{ " + " }, { ".join(",".join(hex(b) for b in hash_pin(user_secrets[u]['pin'])) for u in user_names) + " }"} }};
const u8 PIN_HASHES[][64] = {{ {"{ " + " }, { ".join(",".join(hex(b) for b in hash_pin(user_secrets[u]['pin'])) for u in user_names) + " }"} }};
const u8 user_PIN_hashes[][64] = {{ {"{ " + " }, { ".join(",".join(hex(b) for b in hash_pin(user_secrets[u]['pin'])) for u in user_names) + " }"} }};

#endif // PUBLCS_H
''')

    system_secrets.write(json.dumps({
        "system_symmetric_key": binascii.hexlify(system_symmetric_key).decode(),
        "system_integrity_ecc_key_priv": binascii.hexlify(system_ecc_key_priv).decode(),
        "system_integrity_ecc_key_pub": binascii.hexlify(system_ecc_key_pub).decode(),
        "system_pwhash_master_key": binascii.hexlify(system_pwhash_master_key).decode(),
    }))


def get_args():
    """gets arguments from command line"""
    parser = ArgumentParser(description='main interface to provision system')
    parser.add_argument('--region-list', nargs='+', help='Regions the player is provisioned for.', required=True)
    parser.add_argument('--region-secrets-path', help='Path to region secrets file.', required=True)
    parser.add_argument('--user-list', help='List of users seperated by a space to provision the device for.',
                        nargs='+', required=True)
    parser.add_argument('--user-secrets-path', help='Path to user secrets file generated in createUsers.py',
                        required=True)
    parser.add_argument('--device-dir', help='Path to output any required information for the device.',
                        required=True)
    # parser.add_argument('--outfile', help='location to save system secrets file', required=True)
    args = parser.parse_args()
    args.outfile = "system_secrets.json"
    return args.region_list, args.region_secrets_path, args.user_list, args.user_secrets_path, args.device_dir, args.outfile


if __name__ == '__main__':
    region_names, region_secrets, usernames, user_secrets, device_dir, outfile = get_args()
    print("generating device specific secrets")
    user_secrets = json.load(open(os.path.abspath(user_secrets)))
    region_secrets = json.load(open(os.path.abspath(region_secrets)))
    main(region_names, usernames, user_secrets, region_secrets, device_dir, outfile)
